# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:02:01+00:00

from __future__ import annotations

from datetime import date as date_aliased
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import AnyUrl, BaseModel, Field, RootModel


class AccountGlossaryUploadRequest(BaseModel):
    glossary: bytes = Field(
        ..., description='Glossary file. Currently supported formats: .xlsx, .tbx'
    )


class AccountStyleGuideUploadRequest(BaseModel):
    styleguide: bytes = Field(
        ...,
        description='Style guide file. Currently supported formats: .pdf, .docx, .txt',
    )


class ActiveWidget(BaseModel):
    allow_hash_in_url: Optional[bool] = Field(
        None,
        description='When true, hash params are included in filenames. When false, params are ignored.',
    )
    allow_query_in_url: Optional[bool] = Field(
        None,
        description='When true, query params are included in filenames. When false, params are ignored.',
    )
    auto_detect_source_language: Optional[bool] = Field(
        None,
        description='When true, we will ignore the source language of your project and try to automatically detect the source language of the given content. This is especially useful in environments with unpredictable source contents, such as a chat environment.',
    )
    created_at: Optional[datetime] = Field(
        None,
        description='the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z',
    )
    elements: Optional[str] = Field(
        None, description='Continuous project exclusive elements and rules'
    )
    follow_user: Optional[bool] = Field(
        None,
        description='Specify whether we should follow the user around in your website and automatically translate pages.',
    )
    force_cache_refresh_interval: Optional[bool] = Field(
        None,
        description='Determines whether to force-refresh local browser cache of your translations in certain period of times, no matter if there is a new activity in the project.',
    )
    id: Optional[int] = None
    language_mappings: Optional[str] = Field(
        None, description='Continuous project language mappings'
    )
    live: Optional[bool] = Field(
        None,
        description='Whether ActiveJS should be considered live in an embedded site. Use `false` if you are still testing Active. Go to your Active dashboard and follow links to your website to actually test Active.',
    )
    modify_links: Optional[bool] = Field(
        None,
        description='We can automatically localize the same-domain URLs in your page. The way we localize the URL depends on urlMode configuration. We can either add/update the locale query parameter, or add/update the path of the URL.',
    )
    name: Optional[str] = None
    optimize_per_page: Optional[bool] = Field(
        None,
        description='When true, Active ecosystem will optimize the script and data flows per page, rather than per project. This decreases the bandwidth usage per script, but makes translation publishing more complex and script serving per-page.',
    )
    pages: Optional[str] = Field(None, description='Continuous project page rules')
    path_regex: Optional[str] = Field(
        None, description='Custom regex for path-type URL mode.'
    )
    position: Optional[str] = Field(
        None, description='Options are "bottom-left", "bottom-right", "in-place"'
    )
    query_name: Optional[str] = Field(
        'locale',
        description="Query parameter name to be used with query-type URL mode. Default is 'locale'.",
    )
    reboot_on_url_change: Optional[bool] = Field(
        None, description='When true, Active ecosystem reboots itself when url changes.'
    )
    restricted_domains: Optional[str] = Field(
        None,
        description="JSON string for a list of domains that this widget's API interactions are limited to.",
    )
    sections: Optional[str] = Field(
        None, description='Continuous project section rules'
    )
    test_mode: Optional[bool] = Field(
        None,
        description='Is the Active Widget in test mode? This changes a couple behaviors in the widget to make it easier for you to test and develop your Active integration.',
    )
    theme: Optional[str] = Field(
        None, description='\\"light\\", \\"dark\\" OR custom JSON.'
    )
    token: Optional[str] = Field(
        None,
        description='Token that you should use when you are using this widget on your website.',
    )
    url_change_mode: Optional[str] = Field(
        None,
        description="When a user changes locale (or when we automatically detect and change it for them), we will change the URL of the page they are in. We can do this by actually redirecting the user to the new page, or by simply changing the URL in the address bar via browser's History API. When NULL, we won't apply any URL changes.",
    )
    url_mode: Optional[str] = Field(
        None,
        description="When a user changes locale (or when we automatically detect and change it for them), we will change the URL of the page they are in. We can either change the path of the URL to prefix it with the locale code, or we can add a query parameter to the URL. We also use this mode to detect the locale for the current page when a user directly loads a page. When NULL, locale detection from URL will be disabled (even then, if the user has selected a locale manually, and followUser is enabled, we will still automatically translate the page in user's locale.",
    )
    use_cache: Optional[bool] = Field(
        None,
        description='Should we make use of local browser cache for your visitors? We will refresh the cache when Active JS detects new activity in your project.',
    )
    use_dummy_translations: Optional[bool] = Field(
        None,
        description='When enabled, we will translate your website with dummy content, rather than actually using MT/TM.',
    )
    variables: Optional[str] = Field(
        None, description='Continuous project variable definitions'
    )


class Type(Enum):
    translated = 'translated'
    proofread = 'proofread'


class Address(BaseModel):
    city: Optional[str] = None
    country: Optional[str] = None
    phone: Optional[str] = None
    state: Optional[str] = None
    street: Optional[str] = None
    zip: Optional[str] = None


class AnalyticsCollection(BaseModel):
    anonymousId: Optional[str] = None
    properties: Optional[Dict[str, str]] = None
    sessionId: Optional[str] = None
    type: Optional[str] = None
    userId: Optional[str] = None


class AnalyticsToken(BaseModel):
    jwt: Optional[str] = None


class AsyncOperationStatusEnum(Enum):
    sent = 'sent'
    started = 'started'
    completed = 'completed'
    failed = 'failed'


class Type1(Enum):
    translator = 'translator'
    proofreader = 'proofreader'
    both = 'both'


class AvailableVendorsFilter(BaseModel):
    corporateId: Optional[float] = Field(
        None, description='Corporate account ID to filter for vendor authorization'
    )
    manualWorkPermission: Optional[bool] = Field(
        0, description='Filter vendors for manual work permission'
    )
    sourceLanguage: Optional[str] = Field(None, description='Source language code')
    targetLanguages: Optional[List[str]] = Field(
        None, description='List of target language codes.'
    )
    types: Optional[List[Type1]] = Field(None, description='List of vendor types')


class BillingAddress(Address):
    name: Optional[str] = Field(
        '',
        description='addressing name, such as company name. used in billing address.',
    )


class AnnouncementType(Enum):
    article = 'article'
    case = 'case'
    famous_translators = 'famous-translators'
    sales = 'sales'


class CM(BaseModel):
    user_id: Optional[int] = None


class CancelProjectRequest(BaseModel):
    reason: Optional[str] = Field(None, description='Cancellation reason')


class Average(BaseModel):
    completed_surveys_count: Optional[float] = Field(
        None, description='total number of completed survey count by this client'
    )
    score: Optional[float] = Field(
        None, description='average score for all coompleted surveys'
    )


class Last(BaseModel):
    completion_date: Optional[datetime] = Field(
        None, description='last surveys completion date'
    )
    score: Optional[float] = Field(None, description='score that the client gave us')


class Nps(BaseModel):
    average: Optional[Average] = Field(
        None, description='information for all nps survey that this client completed'
    )
    last: Optional[Last] = Field(None, description='last survey info')


class ClientProjectStat(BaseModel):
    languages: Optional[List[str]] = None
    month: Optional[str] = None
    number_of_projects: Optional[int] = None
    total_spending: Optional[float] = None
    week: Optional[str] = None


class ClientProjectStats(BaseModel):
    stats: Optional[List[ClientProjectStat]] = None


class State(Enum):
    Translated = 'Translated'
    Approved = 'Approved'


class ClientStringTranslation(BaseModel):
    content: Optional[str] = None
    last_changed: Optional[datetime] = Field(
        None,
        description='the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z',
    )
    resource: Optional[str] = None
    resource_id: Optional[str] = None
    state: Optional[State] = None
    target_language: Optional[str] = None


class ClientStringWithTranslations(BaseModel):
    content: Optional[str] = None
    language: Optional[str] = None
    last_changed: Optional[datetime] = Field(
        None,
        description='the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z',
    )
    translations: Optional[List[ClientStringTranslation]] = None


class Status(Enum):
    completed = 'completed'
    unclaimed = 'unclaimed'
    failed = 'failed'
    sent = 'sent'
    waiting = 'waiting'
    waiting_invoice = 'waiting_invoice'


class ContinuousProjectCachedStrings(RootModel[Optional[Dict[str, str]]]):
    root: Optional[Dict[str, str]] = None


class ContinuousProjectDocumentProgressBody(BaseModel):
    documentName: Optional[str] = None
    filterByLanguage: Optional[str] = None


class ContinuousProjectDocumentStringsBody(BaseModel):
    documentName: Optional[str] = None


class ContinuousProjectLanguage(BaseModel):
    code: Optional[str] = None
    is_enabled: Optional[bool] = None


class ContinuousProjectLanguageCache(BaseModel):
    mt: Optional[ContinuousProjectCachedStrings] = None
    nonparsed: Optional[ContinuousProjectCachedStrings] = None
    tm: Optional[ContinuousProjectCachedStrings] = None


class ContinuousProjectUpdateContent(BaseModel):
    analytics_enabled: Optional[bool] = None
    auto_start_postedit: Optional[bool] = None
    is_enabled: Optional[bool] = None
    languages: Optional[List[ContinuousProjectLanguage]] = None
    mt_enabled: Optional[bool] = None
    name: Optional[str] = None
    postedit_enabled: Optional[bool] = None


class ContinuousProjectWordCounts(BaseModel):
    mt: Optional[int] = None
    post_edit: Optional[int] = None
    total: Optional[int] = None


class CorporateAccount(BaseModel):
    billing: Optional[BillingAddress] = None
    domain: Optional[str] = None
    email: Optional[str] = None
    id: Optional[int] = None
    logo: Optional[str] = None
    name: Optional[str] = None
    web_site: Optional[str] = Field(None, description='Deprecated, use `domain`.')


class CreditCard(BaseModel):
    bin: Optional[str] = None
    id: Optional[int] = None
    is_default: Optional[bool] = None
    payment_code: Optional[str] = None


class DeliveryPredictionInLanguage(BaseModel):
    language: Optional[str] = None
    late: Optional[bool] = Field(
        None, description='true for late, false for on-time delivery'
    )
    probability: Optional[float] = None


class DeliveryPredictionPayload(BaseModel):
    projectId: Optional[int] = None


class DeliveryPredictionResponse(BaseModel):
    result: Optional[List[DeliveryPredictionInLanguage]] = None


class DeprecatedStringTranslationContent(BaseModel):
    contents: Optional[List[str]] = None
    source_language: Optional[str] = None
    target_languages: Optional[List[str]] = None


class DocumentSubjects(BaseModel):
    name: Optional[str] = None


class Status1(Enum):
    paid = 'paid'
    pending = 'pending'
    failed = 'failed'


class Earning(BaseModel):
    amount: Optional[float] = None
    currency: Optional[str] = 'usd'
    due_date: Optional[datetime] = Field(
        None,
        description='the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z',
    )
    status: Optional[Status1] = None
    words: Optional[int] = None
    words_approved: Optional[int] = None
    words_translated: Optional[int] = None


class Email(BaseModel):
    email: Optional[str] = None


class Error(BaseModel):
    code: Optional[str] = None
    help: Optional[str] = None
    http_code: Optional[int] = None
    message: Optional[str] = None


class FileAsData(BaseModel):
    data: Optional[str] = Field(
        None, description='Base64 encoded contents of your file.'
    )
    name: Optional[str] = Field(None, description='Name of your file')


class FileNeedsVendor(BaseModel):
    fileId: Optional[int] = None
    guid: Optional[str] = None
    projectId: Optional[int] = None
    reason: Optional[str] = None
    targetLanguage: Optional[List[str]] = None
    taskType: Optional[List[str]] = None


class FilterDates(BaseModel):
    date_from: Optional[datetime] = Field(
        None,
        description='the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z',
    )
    date_to: Optional[datetime] = Field(
        None,
        description='the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z',
    )


class FilterVendorRequest(BaseModel):
    clients: Optional[List[int]] = None
    communication_channel: Optional[List[str]] = None
    corporate_ids_for_auth: Optional[List[int]] = None
    corporates: Optional[List[int]] = None
    country: Optional[List[str]] = None
    created_at: Optional[str] = None
    current_services: Optional[List[str]] = None
    daily_proofreading_capacity: Optional[int] = None
    daily_translation_capacity: Optional[int] = None
    destination_languages: Optional[List[int]] = None
    dtp_software: Optional[List[str]] = None
    email_address: Optional[str] = None
    experience: Optional[List[str]] = None
    first_name: Optional[str] = None
    id: Optional[List[int]] = None
    is_certified_translator: Optional[bool] = None
    is_sworn_translator: Optional[bool] = None
    language_pairs: Optional[List[List[int]]] = None
    last_name: Optional[str] = None
    last_online: Optional[str] = None
    last_worked: Optional[str] = None
    memoq: Optional[int] = None
    memsource: Optional[int] = None
    min_tqs: Optional[float] = None
    omegat: Optional[int] = None
    project_count: Optional[int] = None
    proofreader_experience: Optional[int] = None
    provides_creative_writing_service: Optional[bool] = None
    provides_postedit_service: Optional[bool] = None
    quote_file_subjects: Optional[List[str]] = None
    reference: Optional[str] = None
    sdl_trados: Optional[int] = None
    search: Optional[str] = None
    skype_id: Optional[str] = None
    smartcat: Optional[int] = None
    smartling: Optional[int] = None
    source_languages: Optional[List[int]] = None
    specialization: Optional[List[str]] = None
    status: Optional[List[str]] = None
    subtitle_edit: Optional[int] = None
    subtitle_workshop: Optional[int] = None
    translator_association: Optional[str] = None
    transsuite_2000: Optional[int] = None
    user_working_timezone: Optional[List[str]] = None
    vendor_profile_lsp: Optional[str] = None
    vendor_tags: Optional[List[str]] = None
    vendor_type: Optional[List[str]] = None
    vendor_working_timezone: Optional[List[str]] = None
    word_count: Optional[int] = None
    wordbee: Optional[int] = None
    wordfast: Optional[int] = None
    work_type: Optional[str] = None
    work_with: Optional[str] = None
    working_as: Optional[List[str]] = None
    xbench: Optional[int] = None
    xtm: Optional[int] = None


class Documents(BaseModel):
    extensions: Optional[List[str]] = None
    mimes: Optional[List[str]] = None


class Glossaries(BaseModel):
    extensions: Optional[List[str]] = None


class Styleguides(BaseModel):
    extensions: Optional[List[str]] = None


class Formats(BaseModel):
    documents: Optional[Documents] = None
    glossaries: Optional[Glossaries] = None
    styleguides: Optional[Styleguides] = None


class GetQuotesForDocumentsBody(BaseModel):
    files: Optional[List[int]] = None


class GetQuotesForLanguagesBody(BaseModel):
    languages: Optional[List[str]] = None


class GlossaryUploadRequest(BaseModel):
    glossaries: bytes = Field(
        ...,
        description='You can only add one glossary, even though the name suggests multiple glossaries. This may be updated in the future to support multiple glossaries.',
    )


class Href(BaseModel):
    href: Optional[str] = None


class InstantContentsTranslationResult(BaseModel):
    results: Optional[Dict[str, str]] = Field(
        None, description='a map of source string > translated string.'
    )


class InstantFilesTranslationResult(BaseModel):
    results: Optional[Dict[str, str]] = Field(
        None, description='a map of source file name > base64-encoded translated file.'
    )


class InstantTranslationFilter(BaseModel):
    skipMt: Optional[List[str]] = None
    skipPostEdit: Optional[List[str]] = None


class InstantTranslationRequest(BaseModel):
    contents: Optional[List[str]] = Field(
        None,
        description='Simple list of strings to be translated. You can also choose to upload files instead of strings.',
    )
    documents: Optional[List[FileAsData]] = Field(
        None,
        description='You can add as many files as you want in documents parameter.',
    )
    filters: Optional[InstantTranslationFilter] = None
    meta: Optional[Dict[str, Any]] = Field(
        None,
        description='Free-form meta data to attach to your instant translation request. This can be used in statistics and analytical dashboards.',
    )


class InstantTranslationResult(
    RootModel[Union[InstantContentsTranslationResult, InstantFilesTranslationResult]]
):
    root: Union[InstantContentsTranslationResult, InstantFilesTranslationResult]


class IntegrationsToken(BaseModel):
    token: Optional[str] = None


class InvitedVendor(BaseModel):
    action: Optional[str] = Field(None, description='Action to be taken')
    email_open_rate: Optional[float] = Field(
        None, description='Email opening rate of the vendor'
    )
    is_entered: Optional[bool] = Field(
        None, description='Did the vendor enter the given project'
    )
    is_get_paid: Optional[bool] = Field(None, description='Is vendor get ever paid?')
    is_worked: Optional[bool] = Field(
        None, description='Did the vendor work on the given project'
    )
    is_worked_in_any_project: Optional[bool] = Field(
        None, description='Vendors working status in any project'
    )
    last_project_date: Optional[date_aliased] = Field(
        None, description='Last project date'
    )
    project_status_when_interacted: Optional[float] = Field(
        None,
        description='Project translation percentage when interacted with the vendor',
    )
    registration_date: Optional[date_aliased] = Field(
        None, description='Registration date'
    )
    responsiveness: Optional[float] = Field(
        None, description='Responsiveness of the vendor'
    )
    user_id: Optional[float] = Field(None, description='Id in the Users')
    vendor_id: Optional[float] = Field(None, description='Id in the Vendors')
    vendor_name: Optional[str] = Field(None, description='The name of the vendor')
    vendor_type: Optional[str] = Field(
        None,
        description='Type of the vendor in the given project namely translator or proofreader',
    )


class InvitedVendorsByLanguage(BaseModel):
    invited_vendors: Optional[List[InvitedVendor]] = Field(
        None, description='Invited vendors for this target language'
    )
    target_language: Optional[str] = Field(
        None, description='Target Language that the vendors invited for'
    )


class Language(BaseModel):
    code: Optional[str] = None
    name: Optional[str] = None


class LanguagePair(BaseModel):
    source_language: Optional[str] = None
    target_language: Optional[str] = None


class ReportItem(BaseModel):
    language_pair: Optional[LanguagePair] = None
    spending: Optional[float] = None
    word_count: Optional[int] = None


class LanguageScore(RootModel[float]):
    root: float


class LanguageStringStat(BaseModel):
    project_string_count: Optional[int] = None
    source_language: Optional[str] = None
    tm_string_count: Optional[int] = None


class Source(Enum):
    dropbox = 'dropbox'
    googledrive = 'googledrive'
    icloud = 'icloud'


class LinkedSourceDocument(BaseModel):
    name: Optional[str] = None
    size: Optional[int] = Field(None, description='file size in bytes. optional.')
    source: Optional[Source] = Field(
        None,
        description='Preferred source names are listed as enum. If you have a custom file type, simply enter that name.',
    )
    url: Optional[AnyUrl] = None


class LinksMeta(BaseModel):
    self: Optional[Href] = None


class ListOrderType(Enum):
    asc = 'asc'
    desc = 'desc'


class LocationUpdateContent(BaseModel):
    lat: float = Field(..., description='Latitude of location')
    lon: float = Field(..., description='Longitude of location')
    timestamp: Optional[int] = None


class ManualFile(BaseModel):
    driveFileId: Optional[int] = None
    isProofread: Optional[bool] = None
    isTranslated: Optional[bool] = None
    language: Optional[str] = None
    proofreadingFileId: Optional[int] = None
    translationFileId: Optional[int] = None


class Monetary(BaseModel):
    amount: Optional[float] = None
    currency: Optional[str] = 'usd'


class NewProject(BaseModel):
    callback_url: Optional[str] = Field(
        None,
        description="Optional. If you provide a callback URL, we will send POST callbacks when the status of the current project is changed. Possible status changes are, 'translated', 'proofread', 'completed'.",
    )
    coupon_code: Optional[str] = Field(None, description='Coupon code to redeem')
    custom: Optional[List[str]] = Field(
        None,
        description='Optional. This is a consistent custom data parameter that will be given to you in the response across every request of this project model. Values should be provided like this, custom[my_key] = my_value.',
    )
    documents__: Optional[bytes] = Field(
        None,
        alias='documents[]',
        description='Optional. You can add as many files as you want in documents[] parameter. Or you add your documents later in separate calls.',
    )
    glossaries__: Optional[bytes] = Field(
        None,
        alias='glossaries[]',
        description='Optional. Only one glossary is supported at the moment.',
    )
    source_language: Optional[str] = None
    styleguides__: Optional[bytes] = Field(
        None,
        alias='styleguides[]',
        description='Optional. You can add as many files as you want in styleguides[] parameter. Or you add your style guides later in separate calls.',
    )
    target_languages__: Optional[List[str]] = Field(None, alias='target_languages[]')


class NewSalesActivity(BaseModel):
    subject: Optional[str] = None
    timestamp: Optional[int] = None
    type: Optional[str] = Field(None, description='Activity Type')


class Device(Enum):
    iOS = 'iOS'
    Android = 'Android'
    Chrome = 'Chrome'
    Firefox = 'Firefox'
    Safari = 'Safari'
    Edge = 'Edge'
    Amazon = 'Amazon'
    WindowsPhone = 'WindowsPhone'
    Windows = 'Windows'
    MacOS = 'MacOS'


class Type2(Enum):
    OneSignal = 'OneSignal'


class NotificationSubscription(BaseModel):
    device: Optional[Device] = None
    endpoint: Optional[str] = Field(
        None, description='OneSignal calls this "player ID".'
    )
    type: Optional[Type2] = 'OneSignal'


class OperationStatusEnum(Enum):
    success = 'success'
    error = 'error'


class PackageStatusEnum(Enum):
    started = 'started'
    packaging = 'packaging'
    completed = 'completed'


class PagingLinksMeta(LinksMeta):
    next: Optional[str] = None
    previous: Optional[str] = None


class Paging(BaseModel):
    count: Optional[int] = None
    links: Optional[PagingLinksMeta] = None
    page: Optional[int] = 1
    per_page: Optional[int] = 10
    total_count: Optional[int] = None


class PagingMeta(BaseModel):
    paging: Optional[Paging] = None


class PamMessage(BaseModel):
    message: Optional[str] = Field(None, description='the message to be sent')
    recipients: Optional[List[str]] = Field(
        None, description='name of the recipients in the channel'
    )
    slots: Optional[List[str]] = Field(None, description='contexts for next message')
    thread_id: Optional[str] = Field(None, description='id of the thread')
    thread_key: Optional[str] = Field(
        None, description='the key for thread_id default is project'
    )


class PasswordUpdateContent(BaseModel):
    password: Optional[str] = Field(None, description='New Password')


class Corporate(BaseModel):
    allow_api_invoicing: Optional[bool] = None
    allow_payment_code: Optional[bool] = None
    auto_charge: Optional[bool] = None
    billing: Optional[BillingAddress] = None
    card: Optional[CreditCard] = None
    contact_email_address: Optional[str] = None
    payment_code: Optional[str] = None


class PaymentInfo(BaseModel):
    billing: Optional[BillingAddress] = None
    card: Optional[CreditCard] = None
    cards: Optional[List[CreditCard]] = None
    corporate: Optional[Corporate] = None
    shared_card: Optional[CreditCard] = None


class Permission(RootModel[str]):
    root: str


class PermissionList(BaseModel):
    meta: Optional[PagingMeta] = None
    permissions: Optional[List[Permission]] = None


class PopularLanguagePairs(BaseModel):
    pairs: Optional[List[LanguagePair]] = None


class ProfilePictureUpload(BaseModel):
    profile_picture: bytes = Field(
        ...,
        description='Profile picture file contents. Accepted extensions are png, jpg.',
    )


class ProfileSurvey(BaseModel):
    current_services: Optional[str] = None
    daily_proofreading_capacity: Optional[str] = None
    daily_translation_capacity: Optional[str] = None
    dtp_software: Optional[str] = None
    experience: Optional[str] = None
    is_certified_translator: Optional[str] = None
    is_sworn_translator: Optional[str] = None
    memoq: Optional[str] = None
    memsource: Optional[str] = None
    omegat: Optional[str] = None
    proofreader_experience: Optional[str] = None
    provides_creative_writing_service: Optional[str] = None
    provides_postedit_service: Optional[str] = None
    reference: Optional[str] = None
    sdl_trados: Optional[str] = None
    skype_id: Optional[str] = None
    smartcat: Optional[str] = None
    smartling: Optional[str] = None
    software: Optional[str] = None
    specialization: Optional[str] = None
    subtitle_edit: Optional[str] = None
    subtitle_workshop: Optional[str] = None
    translator_association: Optional[str] = None
    transsuite_2000: Optional[str] = None
    vendor_profile_lsp: Optional[str] = None
    wordbee: Optional[str] = None
    wordfast: Optional[str] = None
    work_type: Optional[str] = None
    work_with: Optional[str] = None
    working_as: Optional[str] = None
    working_timezone: Optional[str] = None
    xbench: Optional[str] = None
    xtm: Optional[str] = None


class ProgressLink(LinksMeta):
    project: Optional[Href] = None


class ProgressSub(BaseModel):
    proofreading: Optional[float] = None
    total: Optional[float] = None
    translation: Optional[float] = None
    word_count: Optional[int] = None


class Price(BaseModel):
    amount: Optional[float] = None
    base_amount: Optional[float] = None
    base_currency: Optional[str] = 'usd'
    currency: Optional[str] = 'usd'
    usd_amount: Optional[float] = Field(
        None,
        description='USD is our base pricing currency. If `currency` is different, this will help.',
    )


class PriceWithoutDiscount(BaseModel):
    amount: Optional[float] = None
    base_amount: Optional[float] = None
    base_currency: Optional[str] = 'usd'
    currency: Optional[str] = 'usd'
    usd_amount: Optional[float] = Field(
        None,
        description='USD is our base pricing currency. If `currency` is different, this will help.',
    )


class WordCountAnalysis(BaseModel):
    base: Optional[float] = None
    duplicate: Optional[float] = None
    exclusion: Optional[float] = None
    final: Optional[float] = None
    tm: Optional[float] = None


class ProjectCompletionReport(BaseModel):
    admin_user_id: Optional[float] = Field(None, description="Assigned admin's user id")
    completion_report_data: Optional[List[InvitedVendorsByLanguage]] = None
    id: Optional[float] = Field(None, description='internal id of the project')
    quote_id: Optional[float] = Field(None, description='quote id of the project')


class ProjectId(BaseModel):
    internal_id: Optional[int] = Field(None, alias='internal-id')
    public_id: Optional[int] = Field(None, alias='public-id')


class ProjectLaunchResponseEnum(Enum):
    started = 'started'


class ProjectLinks(LinksMeta):
    documents: Optional[Href] = None
    glossaries: Optional[Href] = None
    payment: Optional[Href] = None
    quote_pdf: Optional[Href] = Field(None, alias='quote-pdf')
    styleguides: Optional[Href] = None


class PaymentMethod(Enum):
    corporate = 'corporate'
    client = 'client'
    app = 'app'
    credit = 'credit'
    corporate_card = 'corporate_card'


class ProjectPayment(BaseModel):
    bin: Optional[str] = Field(
        None,
        description='Last 4 digits of the credit card you are using one-time. This parameter is only required when stripe_token is provided.',
    )
    budget_code: Optional[str] = Field(
        None, description='Optional with corporate accounts. Not available for others.'
    )
    card_id: Optional[int] = Field(
        None,
        description='Optional. `client`, `app`, `corporate_card` methods require a credit card ID. `credit` method requires Stripe token and bin.',
    )
    payment_code: Optional[str] = Field(
        None, description='Optional. `corporate` payment method requires this.s'
    )
    payment_method: Optional[PaymentMethod] = Field(
        None,
        description="Optional. Determines which method to use for payment. `client`, `app`, `corporate_card` methods require a credit card ID. `credit` method requires Stripe token and bin. `corporate` method follows corporate account policy automatically, either follows invoicing flow or automatically charges corporate's primary card.",
    )
    stripe_token: Optional[str] = Field(
        None,
        description='This is required if you are using a one-time credit card. This is the token generted from frontend via Stripe SDK. If you are using a one-time card with `stripe_token`, you must also provide `bin`, last 4 digits of the card.',
    )


class ProjectSource(Enum):
    api = 'api'
    web = 'web'


class ProjectStatus(Enum):
    pending = 'pending'
    started = 'started'
    completed = 'completed'
    translated = 'translated'
    proofread = 'proofread'


class ProjectTQS(BaseModel):
    is_above_average: Optional[bool] = Field(
        None,
        description='Is this score above or below the average among other vendors in the same project?',
    )
    score: Optional[float] = None
    strings_edited: Optional[int] = Field(
        None,
        description='The number of translated strings by this translator which was edited by a proofreader.',
    )
    strings_translated: Optional[int] = Field(
        None, description='The number of translated strings by this translator.'
    )


class ProjectUpdate(BaseModel):
    callback_url: Optional[str] = Field(
        None,
        description="Optional. If you provide a callback URL, we will send POST callbacks when the status of the current project is changed. Possible status changes are, 'translated', 'proofread', 'completed'.",
    )
    coupon_code: Optional[str] = Field(None, description='Coupon code to redeem')
    custom: Optional[List[str]] = Field(
        None,
        description='Optional. This is a consistent custom data parameter that will be given to you in the response across every request of this project model. Values should be provided like this, custom[my_key] = my_value. If you previously provided one, it will be replaced.',
    )
    source_language: Optional[str] = None
    target_languages__: Optional[List[str]] = Field(None, alias='target_languages[]')


class ProofreaderWithLanguage(BaseModel):
    full_name: Optional[str] = Field(None, description='full name of the proofreader')
    id: Optional[float] = Field(None, description='proofreader id')
    language: Optional[str] = Field(None, description='language code (i.e en-US)')
    vendor_link: Optional[str] = Field(
        None,
        description='link to the vendor that can be only used in motaword admin application',
    )


class QaFilter(BaseModel):
    budget_codes: Optional[List[str]] = None
    categories: Optional[List[str]] = None
    clients: Optional[List[float]] = None
    date_from: Optional[datetime] = Field(
        None,
        description='the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z',
    )
    date_to: Optional[datetime] = Field(
        None,
        description='the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z',
    )
    documents: Optional[List[float]] = None
    projects: Optional[List[float]] = None
    severities: Optional[List[str]] = None
    source_languages: Optional[List[str]] = None
    subjects: Optional[List[str]] = None
    target_languages: Optional[List[str]] = None
    vendors: Optional[List[float]] = None


class RegeneratePreviewResponse(BaseModel):
    link: Optional[Href] = None
    source: Optional[str] = None


class ReportContent(BaseModel):
    activity_type: Optional[str] = Field(None, description='Activity Type')
    message: Optional[str] = Field(None, description='Report Message')


class ReportFilter(BaseModel):
    budget_code: Optional[str] = Field(
        None, description='budget code filter. valid for corporate accounts only.'
    )
    date_from: Optional[datetime] = Field(
        None,
        description='the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z',
    )
    date_to: Optional[datetime] = Field(
        None,
        description='the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z',
    )
    source_languages: Optional[List[str]] = Field(
        None, description='List of source language codes.'
    )
    target_languages: Optional[List[str]] = Field(
        None, description='List of target language codes.'
    )
    users: Optional[List[int]] = Field(
        None,
        description='List of corporate user IDs. Valid for corporate accounts only.',
    )


class Responsivity(BaseModel):
    invited: Optional[int] = None
    month: Optional[str] = None
    notEntered: Optional[int] = None
    onlyEntered: Optional[int] = None
    score: Optional[float] = None
    week: Optional[str] = None
    worked: Optional[int] = None


class ResponsivityList(BaseModel):
    links: Optional[LinksMeta] = None
    responsivity: Optional[List[Responsivity]] = None


class SalesActivity(BaseModel):
    body: Optional[str] = None
    created_at: Optional[int] = Field(None, description='timestamp')
    created_by: Optional[str] = None
    type: Optional[str] = None


class SalesActivityType(Enum):
    EMAIL = 'EMAIL'
    NOTE = 'NOTE'
    INCOMING_EMAIL = 'INCOMING_EMAIL'
    TASK = 'TASK'


class SimpleModel(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None


class SingleString(BaseModel):
    content: Optional[str] = Field(None, description='source string content')
    file_id: Optional[int] = None
    id: Optional[str] = None


class SocialMedia(BaseModel):
    facebook_url: Optional[str] = None
    linkedIn_url: Optional[str] = None
    twitter_url: Optional[str] = None


class Type3(Enum):
    LOCAL_PROJECT = 'LOCAL_PROJECT'
    IMPORTED_TM = 'IMPORTED_TM'


class StringTranslationState(Enum):
    Approved = 'Approved'
    Translated = 'Translated'


class StyleGuideUploadRequest(BaseModel):
    styleguides: bytes = Field(
        ...,
        description='You can only add one style guide, even though the name suggests multiple style guides. This may be updated in the future to support multiple style guides.',
    )


class Subscription(BaseModel):
    downgrade: Optional[List[str]] = Field(None, description='Stripe downgradable plan')
    payment_method: Optional[int] = Field(
        None, description='Stripe subscription plan payment card internal id'
    )
    period_end: Optional[datetime] = Field(None, description='Stripe plan period end')
    plan_id: Optional[str] = Field(None, description='Stripe subscription plan id')
    plan_name: Optional[str] = Field(None, description='Stripe subscription plan name')
    price: Optional[str] = Field(None, description='Stripe plan price')
    products: Optional[List] = None
    schedule_name: Optional[str] = Field(
        None, description='Stripe Scheduled plan period end'
    )
    schedule_start: Optional[datetime] = Field(
        None, description='Stripe Scheduled start date'
    )
    subscription_id: Optional[str] = Field(
        None, description='Stripe subscription id for this project'
    )
    upgrade: Optional[List[str]] = Field(None, description='Stripe upgradable plan')
    withTrial: Optional[Any] = Field(None, description='Stripe plan trial')


class SurveyAnswer(BaseModel):
    answer: Optional[str] = None
    project_id: Optional[int] = None
    question_answer_id: Optional[int] = None
    question_id: Optional[int] = None
    user_id: Optional[int] = None


class SurveyAnswers(BaseModel):
    answers: Optional[List[SurveyAnswer]] = None


class Question(BaseModel):
    enabled: Optional[bool] = None
    format: Optional[str] = None
    id: Optional[int] = None
    question: Optional[str] = None
    text: Optional[str] = None


class SurveyQuestion(BaseModel):
    answers: Optional[List[SimpleModel]] = None
    question: Optional[Question] = None
    question_answers: Optional[List[SimpleModel]] = None


class SurveyQuestions(RootModel[List[SurveyQuestion]]):
    root: List[SurveyQuestion]


class SuspendUserRequest(BaseModel):
    reason: Optional[str] = Field(None, description='Suspension reason for vendor')


class Tag(RootModel[str]):
    root: str


class Token(BaseModel):
    access_token: Optional[str] = None
    expires_in: Optional[int] = None
    refresh_token: Optional[str] = None
    scope: Optional[str] = None
    token_type: Optional[str] = None
    user_id: Optional[int] = None


class AccountStatus(Enum):
    registered = 'registered'
    email_confirmed = 'email_confirmed'
    deleted = 'deleted'
    suspended = 'suspended'
    rejected = 'rejected'
    approved = 'approved'
    resume = 'resume'
    webinar = 'webinar'
    course = 'course'


class TokenError(Error):
    account_status: Optional[AccountStatus] = None


class TokenRequest(BaseModel):
    grant_type: str = Field(
        ...,
        description="OAuth2 grant type. Supports 'client_credentials', 'password', 'refresh_token' or 'user_id'.",
    )
    password: Optional[str] = Field(
        None, description='MW Account password (to be used in password grant type)'
    )
    refresh_token: Optional[str] = Field(
        None, description='Refresh token value for refresh token flow.'
    )
    scope: str = Field(
        ..., description="Authorization scope. Use 'privileged' for private endpoints."
    )
    user_id: Optional[int] = Field(
        None, description='Value for user_id grant type flow.'
    )
    username: Optional[str] = Field(
        None, description='MW Account email (to be used in password grant type)'
    )


class TranslationMemoryUnit(BaseModel):
    sourceLanguage: Optional[str] = None
    sourceText: Optional[str] = None
    targetLanguage: Optional[str] = None
    targetText: Optional[str] = None


class UpdatePaymentInfo(Address):
    bin: Optional[str] = None
    save_as_corporate_primary: Optional[bool] = None
    share_with_corporate_users: Optional[bool] = None
    stripeToken: Optional[str] = None


class UseAsDraftPayload(BaseModel):
    fromFileId: Optional[float] = None
    fromManualTranslationFileId: Optional[float] = None
    toManualTranslationFileId: Optional[float] = None


class UseAsRegularPayload(BaseModel):
    allowOriginalFilePreview: Optional[bool] = None
    allowReviewInManualEditor: Optional[bool] = None
    disableInvitations: Optional[bool] = None
    fromManualTranslationFileId: Optional[float] = None
    hideNumbers: Optional[bool] = None
    recreate: Optional[bool] = None


class Corporate1(BaseModel):
    email: Optional[str] = None
    id: Optional[int] = None
    logo: Optional[str] = None
    name: Optional[str] = None
    phone_number: Optional[str] = None


class Client(BaseModel):
    corporate: Optional[Corporate1] = None
    nps: Optional[float] = None
    subjects: Optional[Dict[str, int]] = None


class Vendor(BaseModel):
    can_work_manual_files: Optional[bool] = None
    email_open_rate: Optional[float] = None
    is_frozen: Optional[bool] = None
    is_proofreader: Optional[bool] = None
    language_pairs: Optional[List[LanguagePair]] = None
    native_language: Optional[str] = Field(None, description='Native language of user')
    pam_tqs: Optional[float] = None
    paypal_email: Optional[str] = None
    profile_survey: Optional[ProfileSurvey] = Field(
        None, description='Vendor Profile Survey answers'
    )
    require_1099: Optional[bool] = None
    tags: Optional[List[Tag]] = None
    tms_user_name: Optional[str] = None
    vendor_type: Optional[str] = None


class UserGroup(BaseModel):
    corporate_id: Optional[int] = None
    id: Optional[int] = None
    name: Optional[str] = None
    permissions: Optional[List[str]] = None


class UserGroupList(BaseModel):
    meta: Optional[PagingMeta] = None
    user_groups: Optional[List[UserGroup]] = None


class UserLinks(LinksMeta):
    login_as: Optional[Href] = Field(None, description='Exculusive users only')
    projects: Optional[Href] = Field(None, description='client users only')
    responsivity: Optional[Href] = Field(None, description='vendor users only')
    stats: Optional[Href] = None


class Notifications(BaseModel):
    phone_number: Optional[str] = Field(None, description='User phone number')
    sms_enabled: Optional[bool] = Field(
        None, description='User sms notification setting'
    )


class UserUpdateContent(Address):
    birthday: Optional[date_aliased] = None
    email: Optional[str] = Field(None, description='Optional. User e-mail.')
    first_name: Optional[str] = Field(None, description='Optional. User first name.')
    id: Optional[int] = Field(
        None, description='Optional. ID of the user being updated.'
    )
    last_name: Optional[str] = Field(None, description='Optional. User last name.')
    notifications: Optional[Notifications] = Field(
        None, description='Notification settings'
    )
    notify: Optional[bool] = Field(
        None,
        description='Notify new user account creation with login information and MotaWord introduction.',
    )
    paypal_email: Optional[str] = Field(
        None, description='Optional. Vendor paypal e-mail'
    )
    require_1099: Optional[bool] = Field(
        None,
        description='Optional. Whether this vendor requires 1099 form in US for their earnings.',
    )
    user_groups: Optional[List[int]] = Field(
        None, description='A list of user group IDs'
    )


class VendorEarningStats(BaseModel):
    total: Optional[float] = Field(
        None,
        description='total amount of USD that this user has earned in the platform so far.',
    )


class VendorProjectRole(Enum):
    translator = 'translator'
    proofreader = 'proofreader'
    both = 'both'


class VendorProjectStats(BaseModel):
    invited: Optional[int] = Field(
        None,
        description='total number of projects that this user was invited to. TODO this key is to replace "total" key due to naming ambiguity.',
    )
    total: Optional[int] = Field(
        None, description='total number of projects that this user was invited to.'
    )
    worked: Optional[int] = Field(
        None, description='total number of projects that this user actually worked on.'
    )


class VendorTag(BaseModel):
    color: Optional[str] = None
    name: Optional[str] = None


class VendorWithNeeds(BaseModel):
    matchedNeeds: Optional[List[FileNeedsVendor]] = None
    userId: Optional[int] = None


class VendorWordStats(BaseModel):
    approved: Optional[int] = Field(
        None, description='total number of words that this user has approved so far.'
    )
    translated: Optional[int] = Field(
        None, description='total number of words that this user has translated so far.'
    )


class Webhook(BaseModel):
    callback_url: Optional[str] = Field(
        None,
        description="Webhook URL. We will send POST callbacks when the status of the current project is changed. Possible status changes are, 'translated', 'proofread', 'completed'.",
    )


class FieldDatamodelCodeGeneratorRootSpecialGetResponse(BaseModel):
    pass


class Type4(Enum):
    active = 'active'


class CorporatesAllGetResponse(RootModel[List[CorporateAccount]]):
    root: List[CorporateAccount]


class TypeFilter(Enum):
    ALL = 'ALL'
    TEXT_DOCUMENTS = 'TEXT_DOCUMENTS'
    PRESENTATIONS = 'PRESENTATIONS'
    SPREADSHEETS = 'SPREADSHEETS'
    PDFS = 'PDFS'
    IMAGES = 'IMAGES'
    SUBTITLES = 'SUBTITLES'
    DESIGNS = 'DESIGNS'
    LOCALIZATION = 'LOCALIZATION'
    WEB = 'WEB'
    STYLE_GUIDES = 'STYLE_GUIDES'
    GLOSSARIES = 'GLOSSARIES'


class OrderBy(Enum):
    id = 'id'
    updated_at = 'updated_at'
    created_at = 'created_at'
    name = 'name'


class WithEnum(Enum):
    preview = 'preview'
    editors = 'editors'


class With(RootModel[List[WithEnum]]):
    root: List[WithEnum]


class DocumentsSubjectsGetResponse(RootModel[List[DocumentSubjects]]):
    root: List[DocumentSubjects]


class With1(RootModel[List[WithEnum]]):
    root: List[WithEnum]


class FormatsGetResponse1(BaseModel):
    pass


class FormatsGetResponse(RootModel[Union[List[Formats], FormatsGetResponse1]]):
    root: Union[List[Formats], FormatsGetResponse1]


class InvitationVendorsPostRequest(RootModel[List[FileNeedsVendor]]):
    root: List[FileNeedsVendor]


class LanguagesGetResponse(RootModel[List[Language]]):
    root: List[Language]


class OrderBy2(Enum):
    id = 'id'
    status = 'status'
    delivery = 'delivery'
    price = 'price'


class WithEnum4(Enum):
    client = 'client'
    vendor = 'vendor'


class Status2(RootModel[List[ProjectStatus]]):
    root: List[ProjectStatus]


class With2(RootModel[List[WithEnum4]]):
    root: List[WithEnum4]


class WithEnum6(Enum):
    client = 'client'
    vendor = 'vendor'
    score = 'score'


class With3(RootModel[List[WithEnum6]]):
    root: List[WithEnum6]


class ActionType(Enum):
    translated = 'translated'
    proofread = 'proofread'
    completed = 'completed'


class WithEnum8(Enum):
    preview = 'preview'
    editors = 'editors'


class With4(RootModel[List[WithEnum8]]):
    root: List[WithEnum8]


class With5(RootModel[List[WithEnum8]]):
    root: List[WithEnum8]


class WithEnum12(Enum):
    preview = 'preview'


class With6(RootModel[List[WithEnum12]]):
    root: List[WithEnum12]


class With7(RootModel[List[WithEnum12]]):
    root: List[WithEnum12]


class Status3(Enum):
    success = 'success'
    already_confirmed = 'already_confirmed'


class Period(Enum):
    monthly = 'monthly'
    weekly = 'weekly'


class IncludeEnum(Enum):
    projects = 'projects'
    documents = 'documents'
    strings = 'strings'


class Include(RootModel[List[IncludeEnum]]):
    root: List[IncludeEnum]


class UserType(Enum):
    vendor = 'vendor'
    all = 'all'


class WithEnum16(Enum):
    user = 'user'


class With8(RootModel[List[WithEnum16]]):
    root: List[WithEnum16]


class UsersTagsGetResponse(RootModel[List[VendorTag]]):
    root: List[VendorTag]


class OrderBy4(Enum):
    id = 'id'
    updated_at = 'updated_at'
    created_at = 'created_at'
    name = 'name'


class Status4(Enum):
    success = 'success'


class Status5(Enum):
    already_confirmed = 'already_confirmed'


class ActiveWidgetList(BaseModel):
    meta: Optional[PagingMeta] = None
    widgets: Optional[List[ActiveWidget]] = None


class ActivityLinks(LinksMeta):
    comments: Optional[Href] = None
    project: Optional[Href] = None


class AddOrUpdateDocumentRequest(BaseModel):
    document: Optional[FileAsData] = None


class AsyncOperationStatus(BaseModel):
    duration: Optional[int] = Field(
        None, description='operation duration in milliseconds'
    )
    key: Optional[str] = None
    message: Optional[Dict[str, Any]] = None
    status: Optional[AsyncOperationStatusEnum] = 'sent'


class BlogArticleLinks(LinksMeta):
    android: Optional[Href] = None
    header_image: Optional[Href] = None
    ios: Optional[Href] = None
    web: Optional[Href] = None


class ClientProfile(BaseModel):
    account_creation_date: Optional[datetime] = Field(
        None,
        description='the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z',
    )
    client_project_count: Optional[float] = Field(
        None, description='total project count that this client sent'
    )
    corporate: Optional[str] = Field(None, description='corporate name')
    corporate_id: Optional[float] = Field(None, description='corporate id')
    corporate_user_count: Optional[float] = Field(
        None, description='total user count in a corporation'
    )
    frequent_file_extension: Optional[str] = Field(
        None,
        description='the file extension for the files that usually this client sent',
    )
    frequent_language_pairs: Optional[List[str]] = Field(
        None, description='frequent language pairs'
    )
    full_name: Optional[str] = Field(None, description='full name of the client')
    growth: Optional[bool] = Field(
        None,
        description='The answer for the question "Is there any growth for this corporate\'s spending". The values can be true, false or null if the corporate is oour client for less than 6 months',
    )
    is_complex: Optional[bool] = Field(
        None,
        description='the answer for the question "Is this client usually sent complex projects?"',
    )
    last_12_months_spending: Optional[float] = Field(
        None, description="corporate's spending in twelve months"
    )
    last_project: Optional[float] = Field(
        None, description='the quote number for the last project of this client'
    )
    last_project_time: Optional[datetime] = Field(
        None,
        description='the creation date of the last project that is sent by this client',
    )
    last_proofreaders: Optional[List[ProofreaderWithLanguage]] = Field(
        None,
        description='list of prooofreaders for the target languages of last project',
    )
    notes: Optional[List[str]] = Field(
        None,
        description='notes that is submited for this client and/or with her projects',
    )
    nps: Optional[Nps] = Field(
        None, description='net promoter score info for this client'
    )
    user_rank_in_project_count: Optional[float] = Field(
        None,
        description='rank of the user in all corporate users for project count. If the user is the most active user foor sending projects her rank is 1',
    )
    user_rank_in_spending: Optional[float] = Field(
        None,
        description='rank of the user in all corporate users for total spending. If the user is the most active user for spending her rank is 1',
    )


class ClientStats(BaseModel):
    document_count: Optional[int] = None
    nps: Optional[float] = None
    started_project_count: Optional[int] = None
    total_discounted: Optional[Monetary] = None
    total_project_count: Optional[int] = None
    total_spending: Optional[float] = None
    translator_count: Optional[int] = None


class ClientStringStats(BaseModel):
    language_counts: Optional[List[LanguageStringStat]] = None
    total_project_strings_count: Optional[int] = None
    total_tm_strings_count: Optional[int] = None


class ClientStrings(BaseModel):
    meta: Optional[PagingMeta] = None
    strings: Optional[List[ClientStringWithTranslations]] = None


class CommentLinks(LinksMeta):
    activity: Optional[Href] = Field(
        None, description='Link to the activity to which this comment was submitted.'
    )
    project: Optional[Href] = None


class CommissionStats(BaseModel):
    balance: Optional[Monetary] = None
    paid: Optional[Monetary] = None
    quote_total: Optional[Monetary] = None
    total: Optional[Monetary] = None


class ContinuousProjectCache(BaseModel):
    meta: Optional[PagingMeta] = None
    translations: Optional[Dict[str, ContinuousProjectLanguageCache]] = None


class ContinuousProjectCosts(BaseModel):
    mt: Optional[Monetary] = None
    post_edit: Optional[Monetary] = None
    saved: Optional[Monetary] = None
    total: Optional[Monetary] = None


class ContinuousProjectLinks(LinksMeta):
    editors: Optional[Dict[str, Href]] = None


class DocumentLinks(LinksMeta):
    admins: Optional[Dict[str, Href]] = None
    download: Optional[Href] = None
    editors: Optional[Dict[str, Href]] = None
    preview_box: Optional[Href] = Field(
        None,
        alias='preview-box',
        description='Box.com URL to preview this document. This URL is temporary. You need to re-fetch the file to refresh the Box.com preview URL. Available for documents and style guides.',
    )
    preview_pdf: Optional[Href] = Field(
        None,
        alias='preview-pdf',
        description='This is our fallback preview URL, providing a PDF file. Use this file to embed in your PDF viewer. Available for documents and style guides.',
    )
    preview_pdf_viewer: Optional[Href] = Field(
        None,
        alias='preview-pdf-viewer',
        description='This is another version of preview-pdf, this time pointing to a preview viewer page on front application. This page requires authentication and comes with its own PDF viewer.',
    )
    progress: Optional[Href] = Field(
        None, description='Progress endpoint URL for this file'
    )
    project: Optional[Href] = None
    strings: Optional[Href] = Field(
        None, description='Strings endpoint URL for this file'
    )
    thumbnail: Optional[Href] = Field(
        None,
        description='Thumbnail preview URL of the document. If doc has a page structure, this is probably only the first page.',
    )


class DocumentUpdates(BaseModel):
    documents__: Optional[List[bytes]] = Field(
        None,
        alias='documents[]',
        description='You can add as many files as you want in documents[] parameter.',
    )
    schemes__: Optional[str] = Field(
        None,
        alias='schemes[]',
        description='JSON string. If your documents have a scheme, as in cases of CSV files, use the same array index keys for `schemes` parameter to specify their schemes. See `Document Schemes` title in the API documentation.',
    )
    source_links__: Optional[List[LinkedSourceDocument]] = Field(
        None,
        alias='source-links[]',
        description='When provided, we will download the files from these URLs, in addition to files provded in `documents` parameter and then save as source documents',
    )


class DocumentUploadRequest(BaseModel):
    documents: Optional[bytes] = Field(
        None,
        description='Single file data. The name is plural to provide a consistent naming convention.',
    )
    schemes: Optional[str] = Field(
        None,
        description='JSON string. If your documents have a scheme, as in cases of CSV files, use the same array index keys for `schemes` parameter to specify their schemes. See `Document Schemes` title in the API documentation.',
    )
    source_link: Optional[LinkedSourceDocument] = Field(None, alias='source-link')


class EarningWithTQS(Earning, ProjectTQS):
    project_id: Optional[int] = None


class Earnings(BaseModel):
    completed: Optional[List[EarningWithTQS]] = None
    ongoing: Optional[List[EarningWithTQS]] = None
    total: Optional[float] = None


class FilterContents(BaseModel):
    budget_codes: Optional[List[str]] = None
    categories: Optional[List[str]] = None
    clients: Optional[List[SimpleModel]] = None
    documents: Optional[List[SimpleModel]] = None
    projects: Optional[List[SimpleModel]] = None
    severities: Optional[List[str]] = None
    source_languages: Optional[List[str]] = None
    subjects: Optional[List[str]] = None
    target_languages: Optional[List[str]] = None
    vendors: Optional[List[SimpleModel]] = None


class Glossary(BaseModel):
    id: Optional[int] = None
    links: Optional[DocumentLinks] = None
    name: Optional[str] = None
    uploaded_at: Optional[int] = Field(None, description='Unix epoch time')


class GlossaryList(BaseModel):
    glossaries: Optional[List[Glossary]] = None
    meta: Optional[PagingMeta] = None


class InvoiceLinks(LinksMeta):
    corporate: Optional[Href] = None
    html: Optional[Href] = None
    json_: Optional[Href] = Field(None, alias='json')
    pdf: Optional[Href] = None
    project: Optional[Href] = None
    view: Optional[Href] = None


class LanguagePairsReport(BaseModel):
    meta: Optional[PagingMeta] = None
    report: Optional[List[ReportItem]] = None


class MachineTranslatedStrings(BaseModel):
    cost: Optional[Monetary] = None
    strings: Optional[List[ClientStringWithTranslations]] = None


class OperationStatus(BaseModel):
    status: Optional[OperationStatusEnum] = 'success'


class PackageStatus(BaseModel):
    status: Optional[PackageStatusEnum] = None


class Progress(ProgressSub):
    languages: Optional[Dict[str, ProgressSub]] = None
    links: Optional[ProgressLink] = None
    project_status: Optional[ProjectStatus] = None


class ProjectLaunchResponse(BaseModel):
    status: Optional[ProjectLaunchResponseEnum] = None


class QaEntry(BaseModel):
    category: Optional[str] = None
    comment: Optional[str] = None
    docId: Optional[str] = None
    editorLink: Optional[str] = None
    end: Optional[int] = None
    inSource: Optional[bool] = None
    isCurrent: Optional[bool] = None
    module: Optional[str] = None
    projectId: Optional[SimpleModel] = None
    severity: Optional[str] = None
    source: Optional[str] = None
    sourceLanguage: Optional[SimpleModel] = None
    start: Optional[int] = None
    state: Optional[str] = None
    targetLanguage: Optional[SimpleModel] = None
    translation: Optional[str] = None
    uniqueKey: Optional[str] = None
    vendor: Optional[SimpleModel] = None


class QaWarnings(BaseModel):
    report: Optional[List[QaEntry]] = None


class SalesActivities(BaseModel):
    activities: Optional[List[SalesActivity]] = None


class StringInSearch(BaseModel):
    file_id: Optional[int] = None
    internal_project_id: Optional[int] = None
    last_updated: Optional[datetime] = Field(
        None,
        description='the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z',
    )
    project_id: Optional[int] = None
    search_score: Optional[float] = None
    source: Optional[str] = None
    status: Optional[StringTranslationState] = None
    string_id: Optional[int] = None
    target: Optional[str] = None
    targets: Optional[List[str]] = None
    tm_name: Optional[str] = None
    type: Optional[Type3] = Field(
        None,
        description='String search result typ from ZNT. Options are LOCAL_PROJECT, IMPORTED_TM. Imported TM results should probably not be visible to end users.',
    )


class StringTranslation(BaseModel):
    content: Optional[str] = Field(None, description='source string content')
    id: Optional[str] = None
    state: Optional[StringTranslationState] = None


class StringWithTranslations(SingleString):
    translations: Optional[Dict[str, StringTranslation]] = None


class StyleGuide(BaseModel):
    id: Optional[int] = None
    links: Optional[DocumentLinks] = None
    name: Optional[str] = None
    uploaded_at: Optional[int] = Field(None, description='Unix epoch time')


class StyleGuideList(BaseModel):
    meta: Optional[PagingMeta] = None
    styleguides: Optional[List[StyleGuide]] = None


class User(BaseModel):
    billing: Optional[BillingAddress] = None
    birthday: Optional[date_aliased] = None
    can_work_manual_files: Optional[bool] = Field(
        None, description='\\@deprecated. use `vendor` key'
    )
    city: Optional[str] = Field(
        None, description='\\@deprecated. use mailing or billing key.'
    )
    client: Optional[Client] = None
    corporate_id: Optional[int] = None
    country: Optional[str] = Field(
        None, description='\\@deprecated. use mailing or billing key.'
    )
    created_at: Optional[int] = Field(None, description='Unix epoch time')
    do_not_contact: Optional[bool] = None
    email: Optional[str] = None
    first_name: Optional[str] = None
    has_pwd: Optional[bool] = None
    id: Optional[int] = None
    is_client: Optional[bool] = None
    is_developer: Optional[bool] = None
    is_proofreader: Optional[bool] = Field(
        None, description='\\@deprecated. use `vendor` key'
    )
    is_prospect: Optional[bool] = None
    is_sales_person: Optional[bool] = None
    is_vendor: Optional[bool] = None
    language_pairs: Optional[List[LanguagePair]] = Field(
        None, description='\\@deprecated. use `vendor` key'
    )
    last_name: Optional[str] = None
    last_seen_online_at: Optional[int] = Field(None, description='Unix epoch time')
    links: Optional[UserLinks] = None
    locale: Optional[str] = Field(None, description='User Locale')
    mailing: Optional[Address] = None
    name: Optional[str] = None
    native_language: Optional[str] = Field(
        None, description='\\@deprecated. Native language of user'
    )
    nps: Optional[float] = Field(
        None,
        description='\\@deprecated. use /stats endpoint for the current nps value.',
    )
    phone_number: Optional[str] = None
    profile_picture_path: Optional[str] = None
    social_media: Optional[SocialMedia] = None
    state: Optional[str] = Field(
        None, description='\\@deprecated. use mailing or billing key.'
    )
    status: Optional[str] = None
    street: Optional[str] = Field(
        None, description='\\@deprecated. use mailing or billing key.'
    )
    timezone: Optional[str] = None
    tms_user_name: Optional[str] = Field(
        None, description='\\@deprecated. use `vendor` key'
    )
    user_groups: Optional[List[UserGroup]] = None
    vendor: Optional[Vendor] = None
    zip_code: Optional[str] = Field(
        None,
        description='\\@deprecated. use mailing or billing key. new key name is "zip".',
    )


class UserList(BaseModel):
    meta: Optional[PagingMeta] = None
    users: Optional[List[User]] = None


class ReportItem1(BaseModel):
    currency: Optional[str] = None
    spending: Optional[float] = None
    user: Optional[User] = None
    word_count: Optional[int] = None


class UsersReport(BaseModel):
    meta: Optional[PagingMeta] = None
    report: Optional[List[ReportItem1]] = None


class VendorInvitationList(BaseModel):
    vendors: Optional[List[VendorWithNeeds]] = None


class VendorProjectPair(BaseModel):
    currency: Optional[str] = 'usd'
    is_proofreader: Optional[bool] = Field(
        None, description='Indicates if the vendor be able to proofred this pair'
    )
    proofreader: Optional[User] = None
    proofreading_rate: Optional[float] = None
    source_language: Optional[str] = Field(None, description='Source language code')
    target_language: Optional[str] = Field(None, description='Target language code')
    translation_rate: Optional[float] = None


class VendorStats(BaseModel):
    earnings: Optional[VendorEarningStats] = None
    projects: Optional[VendorProjectStats] = None
    words: Optional[VendorWordStats] = None


class ResendEmailConfirmationPostResponse(OperationStatus):
    status: Optional[Status3] = 'success'


class FieldUserIdResendEmailConfirmationPostResponse(OperationStatus):
    status: Optional[Status4] = 'success'


class FieldUserIdResendEmailConfirmationPostResponse1(OperationStatus):
    status: Optional[Status5] = 'already_confirmed'


class Activity(BaseModel):
    activity_at: Optional[int] = Field(None, description='Unix epoch time')
    id: Optional[int] = None
    links: Optional[ActivityLinks] = None
    source_text: Optional[str] = Field(None, description='Source text')
    target_text: Optional[str] = Field(
        None,
        description='Target text of the activity, which is actually the translation of the source text.',
    )
    translator: Optional[int] = Field(
        None,
        description='Unique identifier of the translator/proofreader of this activity.',
    )
    type: Optional[Type] = Field(
        None,
        description="Currently there are two available activity types; 'translated', 'proofread'.",
    )


class ActivityList(BaseModel):
    activities: Optional[List[Activity]] = None
    meta: Optional[PagingMeta] = None


class BlogArticle(BaseModel):
    announcement_type: Optional[AnnouncementType] = None
    author: Optional[str] = None
    content: Optional[str] = Field(None, description='Article content')
    created_at: Optional[datetime] = Field(
        None,
        description='the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z',
    )
    excerpt: Optional[str] = Field(None, description='Article excerpt')
    id: Optional[int] = None
    language: Optional[str] = Field(None, description='language code')
    links: Optional[BlogArticleLinks] = None
    slug: Optional[str] = None
    title: Optional[str] = None
    topic: Optional[str] = None


class BlogArticleList(BaseModel):
    articles: Optional[List[BlogArticle]] = None
    meta: Optional[PagingMeta] = None


class Comment(BaseModel):
    comment: str = Field(..., description='Comment text.')
    commented_at: Optional[int] = Field(None, description='Unix epoch time')
    id: Optional[int] = None
    links: Optional[CommentLinks] = None


class CommentList(BaseModel):
    activities: Optional[List[Comment]] = None
    meta: Optional[PagingMeta] = None


class ContinuousProject(BaseModel):
    analytics_enabled: Optional[bool] = Field(
        None,
        description='Should we collect analytics data from Active for this continuous project?',
    )
    auto_start_postedit: Optional[bool] = Field(
        None,
        description='Immediately start post-editing project for translation requests that are applied MT.',
    )
    created_at: Optional[datetime] = Field(
        None,
        description='the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z',
    )
    id: Optional[int] = None
    is_enabled: Optional[bool] = None
    last_activity_at: Optional[datetime] = Field(
        None,
        description='the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z',
    )
    links: Optional[ContinuousProjectLinks] = None
    mt_enabled: Optional[bool] = Field(
        None,
        description='Immediately apply MT on translation requests if they are missing from TM.',
    )
    mt_engine: Optional[str] = Field(
        None,
        description='One of "MOTAWORD", "GOOGLE", "AMAZON", "MS". Default is "MOTAWORD".',
    )
    name: Optional[str] = None
    postedit_enabled: Optional[bool] = Field(
        None,
        description='Get an instant quote for translation requests that are applied MT.',
    )
    source_language: Optional[str] = None
    status: Optional[str] = Field(
        None,
        description='One of "a => ACTIVE", "i => INACTIVE", "d => DELETED", "c => SCHEDULED CANCELLATION", "p => SCHEDULED CHANGE"',
    )
    subscription: Optional[Subscription] = None
    target_languages: Optional[List[str]] = None
    type: Optional[str] = Field(
        None,
        description='Continuous project type. We currently have only 2 types, NULL and "active".',
    )
    word_count: Optional[int] = None


class ContinuousProjectDocument(BaseModel):
    billed_word_count: Optional[int] = None
    id: Optional[str] = None
    links: Optional[DocumentLinks] = None
    name: Optional[str] = None
    post_edit_enabled: Optional[bool] = None
    project_id: Optional[str] = None
    source_language: Optional[str] = None
    target_languages: Optional[List[str]] = None
    word_count: Optional[int] = None


class ContinuousProjectDocumentList(BaseModel):
    documents: Optional[List[ContinuousProjectDocument]] = None
    meta: Optional[PagingMeta] = None


class ContinuousProjectProgress(BaseModel):
    costs: Optional[ContinuousProjectCosts] = None
    progress: Optional[Progress] = None
    word_counts: Optional[ContinuousProjectWordCounts] = None


class ContinuousProjectsList(BaseModel):
    meta: Optional[PagingMeta] = None
    projects: Optional[List[ContinuousProject]] = None


class Document(BaseModel):
    file_type: Optional[str] = Field(None, description='Extension of the file')
    has_custom_package: Optional[bool] = None
    id: Optional[int] = None
    links: Optional[DocumentLinks] = None
    manual_files: Optional[List[ManualFile]] = None
    name: Optional[str] = None
    project_id: Optional[int] = None
    review_in_manual_editor: Optional[bool] = None
    scheme: Optional[Dict[str, Any]] = None
    search_score: Optional[float] = None
    source_language: Optional[str] = None
    subject: Optional[str] = None
    target_languages: Optional[List[str]] = None
    uploaded_at: Optional[int] = Field(None, description='Unix epoch time')
    word_count: Optional[int] = None


class DocumentInSearch(Document):
    search_result_reason: Optional[str] = None


class DocumentList(BaseModel):
    documents: Optional[List[Document]] = None
    meta: Optional[PagingMeta] = None


class Invoice(BaseModel):
    amount: Optional[float] = Field(None, description='Monetary amount')
    base_amount: Optional[float] = Field(None, description='Monetary amount')
    base_currency: Optional[str] = 'usd'
    billing: Optional[BillingAddress] = None
    currency: Optional[str] = 'usd'
    id: Optional[int] = None
    invoice_no: Optional[int] = None
    invoiced_at: Optional[datetime] = Field(
        None,
        description='the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z',
    )
    links: Optional[InvoiceLinks] = None
    status: Optional[str] = None


class Package(PackageStatus):
    key: Optional[str] = Field(
        None,
        description='This is the unique package tracking key. You can use this key to track the current progress of the translation packaging with /package/check call.',
    )


class Project(BaseModel):
    average_scores: Optional[Dict[str, LanguageScore]] = None
    budget_code: Optional[str] = None
    callback_url: Optional[str] = Field(
        None, description='Callback URL to notify when project status changed.'
    )
    can_pam_manage: Optional[bool] = None
    client: Optional[User] = Field(
        None,
        description='User entity for Client. This is only given when project is requested with detailed=true',
    )
    cm_id: Optional[int] = Field(None, description="Assigned admin's id")
    completed_on: Optional[datetime] = Field(
        None,
        description='the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z',
    )
    continuous_project_type: Optional[str] = None
    created_at: Optional[int] = Field(None, description='Unix epoch time')
    custom: Optional[Dict[str, Any]] = Field(
        None, description='Custom data provided while creating a new project.'
    )
    delivery_at: Optional[int] = Field(None, description='Unix epoch time')
    errors: Optional[List[Error]] = Field(
        None,
        description='A list of errors. Visible when creating a project and uploading your documents at the same time, in case of multiple errors.',
    )
    id: Optional[int] = None
    is_api_project: Optional[bool] = None
    is_certified: Optional[bool] = None
    is_continuous: Optional[bool] = None
    is_manual: Optional[bool] = None
    links: Optional[ProjectLinks] = None
    pairs: Optional[List[VendorProjectPair]] = Field(
        None,
        description="Currently authed vendor's available working language pairs in this project. Includes rates per language pair. Includes complex pair logic such as bilingualism, project reverse pair enforcement etc.",
    )
    pivoted_projects: Optional[List[int]] = Field(
        None, description='Quote IDs of pivots'
    )
    price: Optional[Price] = None
    price_without_discount: Optional[PriceWithoutDiscount] = None
    role: Optional[VendorProjectRole] = None
    should_send_client_survey: Optional[bool] = None
    source: Optional[ProjectSource] = Field(
        None,
        description='The source platform where this project was first created. Current options are "api", "web".',
    )
    source_language: Optional[str] = None
    status: Optional[ProjectStatus] = None
    subjects: Optional[List[str]] = None
    target_languages: Optional[List[str]] = None
    tms_name: Optional[str] = Field(
        None,
        description='TMS project name for this MW project. Requires privileged scope.',
    )
    valid_until: Optional[int] = Field(
        None, description='Unix epoch time. Available only if status is `pending`.'
    )
    vendor_word_count: Optional[int] = None
    word_count: Optional[int] = None
    word_count_analysis: Optional[WordCountAnalysis] = None


class ProjectInSearch(Project):
    search_result_reason: Optional[str] = None


class ProjectList(BaseModel):
    meta: Optional[PagingMeta] = None
    projects: Optional[List[Project]] = None


class Result(BaseModel):
    documents: Optional[List[DocumentInSearch]] = None
    projects: Optional[List[ProjectInSearch]] = None
    strings: Optional[List[StringInSearch]] = None


class SearchEverywhereResult(BaseModel):
    meta: Optional[PagingMeta] = None
    result: Optional[Result] = None


class Stats(BaseModel):
    client: Optional[ClientStats] = None
    vendor: Optional[VendorStats] = None


class StringList(BaseModel):
    meta: Optional[PagingMeta] = None
    translations: Optional[List[StringWithTranslations]] = None


class CallbackResult(BaseModel):
    data: Optional[Project] = None
    result: Optional[str] = Field(
        None, description='Callback response returned from `url`.'
    )
    type: Optional[ProjectStatus] = None
    url: Optional[str] = Field(None, description='The URL that received the callback.')


class Commission(BaseModel):
    amount: Optional[Monetary] = None
    date: Optional[datetime] = Field(
        None,
        description='the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z',
    )
    project: Optional[Project] = None
    status: Optional[Status] = None


class CommissionList(BaseModel):
    commissions: Optional[List[Commission]] = None
    meta: Optional[PagingMeta] = None


class ContinuousProjectInvoices(BaseModel):
    invoices: Optional[List[Invoice]] = None
